### ISSUE TITLE
etc. as punctuation

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/UD_Catalan-AnCora#1]
There are a few tokens marked with the `punct` which don't appear to be punctuation in the UD sense.

```
$ cat ~/source/UniversalDependencies/UD_Catalan/ca-ud-train.conllu | grep punct | cut -f2 | grep [a-z] | sort -u
etc
etc.
etcètera
```

**Comment by martinpopel** [comment]
This is marked as [punct-alpha](https://github.com/udapi/udapi-python/blob/3fe163a4c0feb5e844e325024b5f6e6da66c5764/udapi/block/ud/markbugs.py#L165) errors in the automatic `ud.MarkBugs` tests. There are just 20 instances of this error in UD Catalan 2.0, while the total number of errors is 6243. See http://ufallab.ms.mff.cuni.cz/~popel/ca/bugs.html (the Error Overview is based on the whole dataset, but only first 228 sentences are shown).

**Comment by dan-zeman** [comment]
Fixed.
