### ISSUE TITLE
Original Ancora_ca licence has been changed to CC_BY

### ISSUE THREAD

**Issue by cayorodriguez** [UniversalDependencies/UD_Catalan-AnCora#3]
The Ancora licences for SP and CA has been updated to CC_BY, as reflected in Zenodo: https://doi.org/10.5281/zenodo.4762030

Can you use this license also?

Thanks
Carlos

**Comment by dan-zeman** [comment]
Thanks for letting us know! I have changed the README and LICENSE files in both UD_Catalan-AnCora and UD_Spanish-AnCora. It will be used since the upcoming release 2.9 of UD.
