### ISSUE TITLE
Incorrect UTF-8 character

### ISSUE THREAD

**Issue by kleag** [UniversalDependencies/UD_Catalan-AnCora#4]
In sentence CESS-CAT-A-20020301-114-s13 of [UD_Catalan-AnCora](https://github.com/UniversalDependencies/UD_Catalan-AnCora)/ca_ancora-ud-test.conllu, token 52 contains a wrong UTF-8 chracter. It is `mme` (with U+0093, Set Transmit State) while it should be `môme` (with U+00F4).

**Comment by dan-zeman** [comment]
Thanks for the report! The error was already in the source (pre-UD) data. Fixed in UD in the dev branch.
